apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: pdv-mercado
  title: "pdv_mercado"
  description: "Projeto de Banco de Dados "
  annotations:
    github.com/project-slug: "mdlos/pdv_mercado"
spec:
  owner: user:default/guest
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: postgres-db
  title: "Postgres-db"
  description: "Recurso Postgres-db (database)"
  tags:
    - sql
  annotations:
    github.com/project-slug: "mdlos/pdv_mercado"
spec:
  type: database
  lifecycle: experimental
  owner: user:default/guest
  system: pdv-mercado
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  title: "frontend"
  description: "Componente frontend (website)"
  tags:
    - react
    - vite
  annotations:
    github.com/project-slug: "mdlos/pdv_mercado"
spec:
  type: website
  lifecycle: experimental
  owner: user:default/guest
  system: pdv-mercado
  dependsOn:
    - component:default/backend
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend
  title: "backend"
  description: "Componente backend (service)"
  tags:
    - python
    - flask
  annotations:
    github.com/project-slug: "mdlos/pdv_mercado"
spec:
  type: service
  lifecycle: experimental
  owner: user:default/guest
  system: pdv-mercado
  dependsOn:
    - resource:default/postgres-db