apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: pdv-mercado
  title: pdv-mercado
  description: Sistema pdv-mercado analisado automaticamente
  annotations:
    github.com/project-slug: mdlos/pdv_mercado
spec:
  owner: EUBrener
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pdv-mercado-backend-api
  title: pdv-mercado-backend-api
  description: Componente pdv-mercado-backend-api (service)
  tags:
  - python
  - flask
  annotations:
    github.com/project-slug: mdlos/pdv_mercado
spec:
  type: service
  lifecycle: experimental
  owner: EUBrener
  system: pdv-mercado
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pdv-mercado-frontend
  title: pdv-mercado-frontend
  description: Componente pdv-mercado-frontend (website)
  tags:
  - node
  - react
  - vite
  annotations:
    github.com/project-slug: mdlos/pdv_mercado
spec:
  type: website
  lifecycle: experimental
  owner: EUBrener
  system: pdv-mercado
